openapi: "3.0.0"
info:
  description: "Users"
  version: "0.0.1"
  title: "Users"
tags:
  - name: "Users"
    description: "Users service"
servers:
  - url: http://localhost:8080/
    description: "local host"

paths:
    /api/v1/roles:
      post:
            tags:
              - "Roles"
            summary: "Add new role"
            operationId: "addRole"
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    $ref: "./roles-schemas.yaml#/schemas/RoleAddContract"
            responses:
              200:
                description: "Add new role"
                content:
                  application/json:
                    schema:
                      $ref: "./roles-schemas.yaml#/schemas/UserRoleContract"

      get:
        tags:
          - "Roles"
        summary: "Get all roles"
        operationId: "getRoles"
        responses:
          200:
            description: "List of roles"
            content:
              application/json:
                schema:
                  type: "array"
                  items:
                    $ref: "./roles-schemas.yaml#/schemas/UserRoleContract"
components:
  parameters:
    pageParam:
      name: "page"
      in: "query"
      description: "pagination page"
      required: false
      schema:
        type: "integer"
        default: 0
    sizeParam:
      name: "size"
      in: "query"
      description: "pagination size"
      required: false
      schema:
        type: "integer"